In [1]:
#1 ndarray 객체 Z의 원소들로부터 정수 부분만 추출
# np.random.seed(0)
# Z=np.random.uniform(0, 10, 10)
import numpy as np
np.random.seed(0)
Z=np.random.uniform(0, 10, 10)
print(Z)
print(Z//1)

[5.48813504 7.15189366 6.02763376 5.44883183 4.23654799 6.45894113
 4.37587211 8.91773001 9.63662761 3.83441519]
[5. 7. 6. 5. 4. 6. 4. 8. 9. 3.]


In [ ]:
#또다른 풀이
np.random.seed(0) 
Z = np.random.uniform(0,10,10)
print(Z)
print(Z-(Z%1))
print(Z.astype(int))
print(np.trunc(Z))
print(np.floor(Z))

In [2]:
#2 행의 값이 0~4 정수 데이터로 구성된 5x5 2차원배열 객체 생성
import numpy as np
a = np.random.randint(0, 5, [5,5])
print(a)

[[0 1 1 0 1]
 [4 3 0 3 0]
 [2 3 0 1 3]
 [3 3 0 1 1]
 [1 0 2 4 3]]


In [ ]:
#또다른 풀이
Z = np.random.randint(0, 5, 25).reshape(5,5) 
print(Z)

#또다른 풀이
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

In [4]:
#3 random()함수로 10개의 원소를 생성하고, 생성된 원소 중 최대값을 0으로 변경하시오
import numpy as np
np.random.seed(4)
a = np.random.random(10)
print('변경 전 :', a)
print('최댓값 :', np.argmax(a))
a[np.argmax(a)] = 0
print('변경 후 :', a)

변경 전 : [0.96702984 0.54723225 0.97268436 0.71481599 0.69772882 0.2160895
 0.97627445 0.00623026 0.25298236 0.43479153]
최댓값 : 6
변경 후 : [0.96702984 0.54723225 0.97268436 0.71481599 0.69772882 0.2160895
 0.         0.00623026 0.25298236 0.43479153]


In [ ]:
#또다른 풀이
import numpy as np
np.random.seed(0)
Z = np.random.rand(10)
for i in range(10):
    if Z[i] == max(Z):
        Z[i] = 0
print('변경 후 :', Z)

import numpy as np
np.random.seed(0)
Z = np.random.rand(10)
Z.sort()         ######벡터이니까 for 안 쓰고 이렇게 하는 게 좋음
Z[9] = 0
print(Z)

import numpy as np 
np.random.seed(0)
Z = np.random.random(10)
print('변경 전 :', Z)
Z[Z.argmax()] = 0         ######벡터이니까 for 안 쓰고 이렇게 하는 게 좋음
print('변경 후 :', Z)

In [5]:
#4 크기가 10인 랜덤 벡터를 생성하고 벡터의 원소를 오름차순으로 정렬하시오
import numpy as np
np.random.seed(4)
a = np.random.random(10)
a.sort()
print(a)

[0.00623026 0.2160895  0.25298236 0.43479153 0.54723225 0.69772882
 0.71481599 0.96702984 0.97268436 0.97627445]


In [7]:
#5 Z배열 객체에서 빈도수가 가장 높은 값을 찾아 출력하시오
#Z = np.random.randint(0, 10, 50)
import numpy as np
np.random.seed(3)
Z = np.random.randint(0, 10, 50)
print(Z)
print('빈도수가 가장 높은 값 :',np.bincount(Z).argmax())

[8 9 3 8 8 0 5 3 9 9 5 7 6 0 4 7 8 1 6 2 2 1 3 5 8 1 8 7 8 1 0 5 4 1 5 4 7
 6 0 0 9 2 4 5 8 8 7 5 1 1]
빈도수가 가장 높은 값 : 8


In [9]:
#6 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
import numpy as np
a = np.random.randint(1,7,100)
print(a.mean())

3.73


In [10]:
#7 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 
# 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라
import numpy as np
a = [10000+int(n*10) for n in np.random.normal(0,1,size=250)]
print(a)

[10005, 9996, 9996, 10008, 9995, 9984, 9991, 10000, 10001, 10012, 9993, 10007, 10004, 9999, 10008, 10004, 9992, 10010, 9988, 10000, 10000, 10004, 9993, 10000, 9999, 10009, 9993, 10000, 9998, 9988, 10026, 10000, 9986, 10014, 9990, 10003, 10008, 9994, 9996, 9995, 9999, 9984, 9988, 9999, 10010, 10006, 10017, 10006, 9995, 9999, 9980, 9991, 9990, 10002, 10006, 9995, 9995, 9985, 9999, 10002, 10004, 9993, 10019, 10011, 10000, 9995, 9997, 10001, 10000, 10004, 10007, 10013, 10011, 9999, 10003, 9997, 9995, 10019, 9996, 10019, 9997, 10002, 10010, 10000, 10003, 9998, 9996, 9999, 9994, 10016, 9999, 10017, 9974, 10000, 10005, 9998, 10010, 10006, 9998, 10004, 10028, 10002, 10002, 9996, 10001, 9988, 9999, 10024, 10010, 10006, 10011, 10018, 10005, 10020, 10010, 10001, 10017, 9977, 9995, 10002, 9991, 9999, 9994, 9994, 10027, 10006, 10000, 10013, 9998, 10008, 10003, 10016, 9986, 10007, 10001, 9989, 10010, 9992, 10016, 10005, 10006, 10000, 10009, 9982, 10000, 9994, 10002, 10000, 10006, 9992, 10018, 10023,

In [11]:
# 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
import numpy as np
a = np.random.randint(0,2,10)
print(a)

[1 1 0 1 0 0 0 0 1 1]
