In [1]:
# Q. numpy를 np로 가져오고 버전 확인
import numpy as np
print(np.version.version)

1.22.4


In [3]:
# Q. 0에서 9까지의 숫자로 구성된 1D 배열 생성
import numpy as np
a = np.random.randint(0,10,10)
print(a)

[0 5 5 8 6 8 3 1 1 2]


In [8]:
# Q. 모든 True의 3×3 numpy 배열 생성
import numpy as np
t = np.zeros((3,3))
t = (t == 0)
print(t) 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
# Q. 1D 배열에서 모든 홀수를 추출
# 입력 > arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# 출력 > array([1, 3, 5, 7, 9])
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr%2!=0])

[1 3 5 7 9]


In [12]:
# Q. 모든 홀수 arr를 -1 로 바꿉니다.
# 입력 > arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# 출력 > array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [13]:
# Q. arr의 모든 홀수를 변경하지 않고 -1로 바꿉니다
# 입력 > arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# 출력 > array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
#           arr는 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_odd = arr.flatten()
arr_odd[arr_odd%2!=0] = -1
print(arr_odd)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [14]:
# Q. 1D 배열을 2행이 있는 2D 배열로 변환
# 입력 > np.arange(10)
# 출력 > array([[0, 1, 2, 3, 4],
#                   [5, 6, 7, 8, 9]])
import numpy as np
a = np.arange(10)
a = a.reshape(2,5)
print(a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
# Q. 두 개의 어레이를 수직으로 쌓기
# 입력 > a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# 출력 >  array([[0, 1, 2, 3, 4],
#        [5, 6, 7, 8, 9],
# 	     [1, 1, 1, 1, 1],
# 	     [1, 1, 1, 1, 1]])
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.vstack([a,b])
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
# Q. 두 개의 어레이를 수평으로 쌓기
# 입력 > a = np.arange(10).reshape(2,-1)
#           b = np.repeat(1, 10).reshape(2,-1)

# 출력 >  array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                     [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.hstack([a,b])
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [30]:
# Q. 하드코딩 없이 아래 입력 배열만 사용 출력과 같은 패턴을 만드시오
# 입력 > a = np.array([1,2,3])
# 출력 > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
import numpy as np
a = np.array([1,2,3])
result1 = np.dstack([a,a,a]).ravel()
result2 = np.tile(a, 3)
print(np.hstack([result1, result2]))


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [38]:
# Q 두 파이썬 numpy 배열 사이의 공통 항목  출력
# 입력 > a = np.array([1,2,3,2,3,4,3,4,5,6])
#          b = np.array([7,2,10,2,7,4,9,4,9,8])
# 출력 >  array([2, 4])
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
print(c)

[2 4]


In [39]:
# Q. 배열 a에서 b 배열에 있는 모든 항목을 제거합니다.
# 입력 > a = np.array([1,2,3,4,5])
#           b = np.array([5,6,7,8,9])
# 출력 > array([1,2,3,4])
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
print(c)

[1 2 3 4]


In [52]:
# Q. a, b두 배열의 요소가 일치하는 위치를 출력
# 입력 > a = np.array([1,2,3,2,3,4,3,4,5,6])
#           b = np.array([7,2,10,2,7,4,9,4,9,8])
# 출력 > (array([1, 3, 5, 7]),)
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = []
[c.append(idx) for idx in range(len(a)) if a[idx] == b[idx]]
c = np.array(c)
print(c)

[[1, 3, 5, 7]]


In [77]:
# Q. a배열에서  5에서 10 사이의 모든 항목을 에서 가져옵니다 
# 입력 > a = np.array([2, 6, 1, 9, 10, 3, 27])
# 출력 > ( array ([ 6 , 9 , 10 ]),)  
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
b = np.arange(5, 11)
c = []
#[c.append(value) for value in a if b.any(a)]
#c = np.array(c)
print(a>=5)

[False  True False  True  True False  True]


Q. maxx두 개의 스칼라에서 작동하는 함수를 두 개의 배열에서 작동하도록 변환하시오
- 입력 > def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)  #호출
5             #출력

출력 > a = np.array([5, 7, 9, 8, 6, 4, 5])
          b = np.array([6, 3, 4, 8, 9, 7, 1])
          pair_max(a, b)     #함수 호출
          array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])  #출력



In [13]:
import numpy as np
def pair_max(x, y):
    return np.maximum(x,y)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [83]:
# Q.  2d numpy 배열에서 배열의 1열과 2열을 바꿉니다
# 입력 > arr = np.arange(9).reshape(3,3)
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [86]:
# Q. 2D 배열의 행을 뒤집습니다.
# 입력 >  arr = np.arange(9).reshape(3,3)
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[[2,1,0], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [87]:
# Q. 2D 배열의 열을 뒤집습니다.
# 입력 >  arr = np.arange(9).reshape(3,3)
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, [2,1,0]])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [88]:
# Q. 5에서 10 사이의 임의의 십진수를 포함하는 5x3 모양의 2D 배열을 만듭니다.
import numpy as np
a = np.random.randint(5,11,[5,3])
print(a)

[[10 10 10]
 [ 8  5  9]
 [10  6  8]
 [ 7  9 10]
 [ 7  7 10]]


In [92]:
# Q. 5에서 10 사이의 임의의 부동 소수점을 포함하는 5x3 모양의  2D 배열 만듭니다.
import numpy as np
a = np.random.uniform(5,11,[5,3])
print(a)

[[ 7.18829219  9.60003241  6.59439589]
 [10.88121094  8.88779184  7.26171435]
 [ 8.13081973  8.92808636 10.46453042]
 [ 7.43873561  6.68018073  8.01001313]
 [ 8.82610813  8.59224259 10.45835955]]


In [93]:
# Q. numpy 배열의 소수점 이하 세 자리만 출력합니다.
# 입력 > rand_arr = np.random.random((5,3))
import numpy as np
rand_arr = np.random.random((5,3))
print(rand_arr.round(3))

[[0.415 0.964 0.345]
 [0.294 0.442 0.875]
 [0.175 0.802 0.7  ]
 [0.535 0.747 0.208]
 [0.343 0.665 0.761]]


In [97]:
# Q.  과학적 표기법(예: 1e10)을 억제하여 numpy 배열을 예쁘게 출력하시오
# 입력 > np.random.seed(100)
#           rand_arr = np.random.random([3,3])/1e3

# 출력 > array([[ 0.000543,  0.000278,  0.000425],
#                   [ 0.000845,  0.000005,  0.000122],
#                   [ 0.000671,  0.000826,  0.000137]])
import numpy as np
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(precision=6, suppress=True)
print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [99]:
# Q.   numpy 배열의 출력에 인쇄되는 항목 수를 최대 6개 요소로 제한하시오
# 입력 >  a = np.arange(15)
# 출력 >  array([ 0,  1,  2, ..., 12, 13, 14])
import numpy as np
a = np.arange(15)
np.set_printoptions(threshold=7)
print(a)

[ 0  1  2 ... 12 13 14]


In [100]:
# Q.  출력에 데이터 항목이 제한된 numpy 배열의  모든 데이터를 출력하시오
# 입력 > np.set_printoptions(threshold=6)
#           a = np.arange(15)
# 출력 > array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
import numpy as np
np.set_printoptions(threshold=np.inf)
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
